#!/bin/bash

#SBATCH --ntasks=4  				# Request number of processes (if >40, multiple nodes are used in Iridis5) 
#SBATCH --job-name=test      	    # Job name
#SBATCH --time=00:05:00	 		    # Walltime - leave time to write flow 
#SBATCH --mail-type=ALL				# Mail notifications
#SBATCH --signal=B:USR1@60

your_cleanup_function()
{
    echo "function your_cleanup_function called at $(date)"
    touch ./.kill
}

# call your_cleanup_function once we receive USR1 signal
trap 'your_cleanup_function' USR1

echo "starting calculation at $(date)"
rm ./.kill

module load openmpi/3.1.4/gcc-4.8.5
module load python/3.7.3

python3 run.py
