#!/bin/bash

#SBATCH -p gpu
#SBATCH --gres=gpu:1
#SBATCH --ntasks=16  				# Request number of processes (if >40, multiple nodes are used in Iridis5) 
#SBATCH --job-name=gpu_shit      	    # Job name
#SBATCH --time=08:00:00	 		    # Walltime - leave time to write flow 
#SBATCH --mail-type=ALL				# Mail notifications
#SBATCH --signal=SIGINT@60

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module load texlive
module load python
source ~/postproc/bin/activate

python3 poly_model.py
